baseURL = "https://dmiracle.github.io/forestio-test/"
languageCode = "en-us"
title = "Provider Map"
copyright = "Strangeworks"
theme = "ananke"
pluralizelisttitles = false

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = "/imgs/favicon-32x32.png"
  site_logo = "imgs/sw_horz_reverse_rgb.png"
  description = "Quantum hardware and software page"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/strangeworks/q-software-map"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-orange"
  featured_image = "/imgs/swlogo.png"
  # recent_posts_number = 2
